development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:b8a516724d2ecb8aff1aa20359aa6458@soapfish.redistogo.com:9991/
#  channel_prefix: ugatu_production
